routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');

// Sobreescribe la ruta de logout para que soporte get
Route::get('logout', function () {

    if (Auth::check()) {
        $isInfluencer = Auth::user()->isCelebridad();

        Auth::logout();
        request()->session()->flush();
        request()->session()->regenerate();

        if ($isInfluencer) {
            return redirect('influenciadores/login');
        }
    }

    return redirect('/');
});

Auth::routes();

Route::resource('servicios', 'ServiciosController');

Route::group(['prefix' => 'auth/twitter', 'namespace' => 'Auth'], function () {
    Route::get('login', 'TwitterController@redirectToProvider')->name('twitter.login');
    Route::get('logout', 'TwitterController@logout')->name('twitter.logout');
    Route::get('callback', 'TwitterController@handleProviderCallback')->name('twitter.callback');
    // Route::get('posttweet', 'TwitterController@postTweet')->name('twitter.post');
});

Route::group(['prefix' => 'auth/facebook', 'namespace' => 'Auth'], function () {
    Route::get('login', 'FacebookController@redirectToProvider')->name('facebook.login');
    Route::get('logout', 'FacebookController@logout')->name('facebook.logout');
    Route::get('callback', 'FacebookController@handleProviderCallback')->name('facebook.callback');
    Route::get('publicar', 'FacebookController@postTweet')->name('facebook.post');
});

Route::get('influenciadores/login', 'InfluenciadorController@login');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['perfil']], function () {
        Route::get('/', 'RedirectController@index')->name('index');
        Route::get('palabrasclaves/searchbytext', 'PalabraClaveController@searchByText');
        Route::get('agencias/logotipo', 'AgenciaController@getLogotipo');
        Route::get('agencias/home', 'AgenciaController@home');
        Route::get('marcas/logotipo', 'MarcaController@getLogotipo');
        Route::get('marcas/byagencia', 'MarcaController@getByAgencia');
        Route::get('productos/imagen', 'ProductoController@getImagen');
        Route::get('productos/bymarca', 'ProductoController@getByMarca');

        Route::get('influenciadores/vincular/twitter', 'VincularController@twitterRedirectToProvider');
        Route::get('influenciadores/vincular/twittercallback', 'VincularController@twitterHandleProviderCallback');
        Route::get('influenciadores/vincular/facebook', 'VincularController@facebookRedirectToProvider');
        Route::get('influenciadores/vincular/instagram', 'VincularController@instagramRedirectToProvider');
        Route::get('influenciadores/vincular/youtube', 'VincularController@youtubeRedirectToProvider');
        Route::get('influenciadores/vincular/snapchat', 'VincularController@snapchatRedirectToProvider');


        Route::get('influenciadores/miscampanas/{id}/posts', 'InfluenciadorController@miscampanasposts');
        Route::get('influenciadores/miscampanas', 'InfluenciadorController@miscampanas');
        Route::get('influenciadores/miinfo', 'InfluenciadorController@miinfo');
        Route::get('influenciadores/searchbytext', 'InfluenciadorController@searchByText');
        Route::get('influenciadores/advancedsearch', 'InfluenciadorController@advancedSearch');
        // Route::get('influenciadores/sincronizacion', 'InfluenciadorController@sincronizacion');
        // Route::get('influenciadores/sincronizarjsons', 'InfluenciadorController@sincronizarjsons');
        // Route::get('influenciadores/sincronizarperfil/{id}', 'InfluenciadorController@sincronizarperfil');
        Route::get('influenciadores/catalogo', 'InfluenciadorController@catalogo');
        Route::get('profile/general/{id}', 'ProfileController@getGeneral');
        Route::get('profile/crecimiento/{id}', 'ProfileController@getCrecimientoSeguidores');
        Route::get('profile/topseguidores/{id}', 'ProfileController@getTopSeguidores');
        Route::get('profile/topword/{id}', 'ProfileController@getTopWord');
        Route::get('profile/hashtag/{id}', 'ProfileController@getHashtag');
    });

    Route::post('/password/change', 'Auth\ChangePasswordController@update');
    Route::get('usuarios/perfil', 'UsuarioController@perfil')->name('usuarios.perfil');
    Route::put('usuarios/updateperfil/{id?}', 'UsuarioController@updateperfil')->name('usuarios.updateperfil');
    Route::resource('usuarios', 'UsuarioController');
    Route::resource('palabrasclaves', 'PalabraClaveController');

    Route::resource('agencias', 'AgenciaController');
    Route::resource('marcas', 'MarcaController');
    Route::resource('productos', 'ProductoController');

    Route::resource('campanas', 'CampanaController');
    Route::get('campanas/{id}/terminos', 'CampanaController@downloadTerminos');
    Route::get('campanas/{id}/estadisticas', 'CampanaController@estadisticas');
    Route::get('campanas/{id}/graficas/top-locations', 'CampanaController@graficaTopLocations');
    Route::get('campanas/{id}/graficas/posts-per-hour', 'CampanaController@graficaPostsPerHour');
    Route::get('campanas/{id}/graficas/share-social', 'CampanaController@graficaShareSocial');
    Route::get('campanas/{id}/graficas/shares-twitter', 'CampanaController@graficaSharesTwitter');

    Route::post('influenciadores/clic', 'InfluenciadorController@clic');
    Route::post('influenciadores/aprobarpublicaciones', 'InfluenciadorController@aprobarpublicaciones');
    //Route::get('influenciadores/searchlugarnacimientobytext', 'InfluenciadorController@searchLugarNacimientoByText');
    //Route::get('influenciadores/searchpaisbytext', 'InfluenciadorController@searchPaisByText');
    Route::resource('influenciadores', 'InfluenciadorController');

    Route::get('influenciadores/{influeciadore}/{q}', 'InfluenciadorController@showCustom');

    // estadísticas influencer profile
    Route::get('influenciadores/{id}/graficas/crecimiento-followers', 'InfluenciadorController@crecimientoFollowers');
    Route::get('influenciadores/{id}/graficas/interacciones-mes', 'InfluenciadorController@interaccionesMensual');

    Route::post('publicaciones/publicar/{id?}', 'PublicacionController@publicar');
    Route::post('publicaciones/aprobar', 'PublicacionController@aprobar');
    Route::resource('publicaciones', 'PublicacionController');

    Route::post('publicacionesxcampana/aceptarpropuesta', 'PublicacionXInfluenciadorXCampanaController@aceptarpropuesta');
    Route::post('publicacionesxcampana/rechazarpropuesta', 'PublicacionXInfluenciadorXCampanaController@rechazarpropuesta');
    Route::delete('publicacionesxcampana/destroy/{id?}', 'PublicacionXInfluenciadorXCampanaController@destroy');
    Route::put('publicacionesxcampana/update/{id?}', 'PublicacionXInfluenciadorXCampanaController@update');

    Route::post('influenciadoresxcampana/aceptarpropuesta', 'InfluenciadorXCampanaController@aceptarpropuesta');
    Route::post('influenciadoresxcampana/rechazarpropuesta', 'InfluenciadorXCampanaController@rechazarpropuesta');
    Route::delete('influenciadoresxcampana/destroy/{id?}', 'InfluenciadorXCampanaController@destroy');
    Route::put('influenciadoresxcampana/update/{id?}', 'InfluenciadorXCampanaController@update');

    Route::resource('chat', 'ChatController');

    Route::resource('logeventos', 'LogeventoController', ['only' => ['index']]);
});

app/Models/Campana.php
<?php

namespace App\Models;

use DB;
use Exception;
use App\Helpers\WordCloudGetter;
// use App\Models\Etl\Twitter\EstadisCampanaTopFollower;

class Campana extends BaseModel
{
    protected $table = 'campana';

    protected $fillable = [
        'agencia_id',
        'tipo_campana_id',
        'industria_id',
        'marca_id',
        'producto_id',
        'nombre',
        'hashtags',
        'fecha_desde',
        'presupuesto',
        'fecha_hasta',
        'activo',
    ];

    public $rules_create = [
        'agencia_id'      => 'bail|required|integer|exists:agencia,id',
        'tipo_campana_id' => 'bail|required|integer|exists:tipo_campana,id',
        'industria_id'    => 'bail|required|integer|exists:industria,id',
        'marca_id'        => 'bail|integer|exists:marca,id',
        'producto_id'     => 'bail|integer|exists:producto,id',
        'nombre'          => 'bail|required|min:3|max:45',
        'hashtags'        => 'bail|required|min:3|max:200',
        'fecha_desde'     => 'bail|required|date_format:Y-m-d',
        'fecha_hasta'     => 'bail|required|date_format:Y-m-d|after:fecha_desde',
        'presupuesto'     => 'bail|required|numeric',
        'activo'          => 'bail|required|integer|in:0,1',
    ];

    public $rules_update = [
        'agencia_id'      => 'bail|integer|exists:agencia,id',
        'tipo_campana_id' => 'bail|integer|exists:tipo_campana,id',
        'industria_id'    => 'bail|required|integer|exists:industria,id',
        'marca_id'        => 'bail|nullable|integer|exists:marca,id',
        'producto_id'     => 'bail|nullable|integer|exists:producto,id',
        'nombre'          => 'bail|string|min:3|max:45',
        'hashtags'        => 'bail|string|min:3|max:200',
        'fecha_desde'     => 'bail|date_format:Y-m-d',
        'fecha_hasta'     => 'bail|date_format:Y-m-d',
        'presupuesto'     => 'bail|required|numeric',
        'activo'          => 'bail|integer|in:0,1',
    ];

    public static $labels = [
        'agencia_id'      => 'Agencia',
        'tipo_campana_id' => 'Objetivo de la Campaña',
        'industria_id'    => 'Industria',
        'marca_id'        => 'Marca',
        'producto_id'     => 'Producto',
        'nombre'          => 'Nombre',
        'hashtags'        => 'hashtags',
        'fecha_desde'     => 'Desde',
        'fecha_hasta'     => 'Hasta',
        'presupuesto'     => 'Presupuesto',
        'activo'          => 'Activo',
        'influenciadores' => 'Influenciadores',
    ];

    public $influenciadores = null;
    public $influenciadoresAprobados = null;
    public $estadisticas = null;

    /**
     * Guarda las interacciones (cantidades) de la publicación
     * retweets, favorites, replies, total_followers_rt, fecha
     *
     * @var array
     */
    public $interacciones = [];

    /**
     * Guarda suma del total de seguidores de los influenciadores que
     * aceptaron participar en la campaña
     *
     * @var int
     */
    public $alcance_organico = 0;

    /**
     * Obtiene el presupuesto en formato de moneda
     *
     * @param  int  $value
     * @return string
     */
    public function getPresupuestoCurrencyAttribute()
    {
        return '$ ' . number_format(doubleval($this->presupuesto)) . ' MXN';
    }

    /**
     * Obtiene las registros de las tablas con las que tiene relación el modelo
     *
     * @param boolean $withLabels Para incluir las etiquetas como primer elemento del array
     * @return array
     */
    public static function getCatalogs($withLabels = true)
    {
        $cataglos = [];

        $catalogs['agencia'] = Agencia::orderBy('nombre', 'asc')
            ->where('activo', 1)
            ->get()
            ->pluck('nombre', 'id');

        $catalogs['tipo_campana'] = TipoCampana::orderBy('tipo', 'asc')
            ->get()
            ->pluck('tipo', 'id');

        $catalogs['industria'] = Industria::orderBy('nombre', 'asc')
            ->where('activo', 1)
            ->get()
            ->pluck('nombre', 'id');

        $catalogs['marca'] = Marca::orderBy('nombre', 'asc')
            ->where('activo', 1)
            ->get()
            ->pluck('nombre', 'id');

        $catalogs['producto'] = Producto::orderBy('nombre', 'asc')
            ->where('activo', 1)
            ->get()
            ->pluck('nombre', 'id');

        if ($withLabels == true) {
            $catalogs['agencia']->prepend(self::$labels['agencia_id'], '');
            $catalogs['tipo_campana']->prepend(self::$labels['tipo_campana_id'], '');
            $catalogs['industria']->prepend(self::$labels['industria_id'], '');
            $catalogs['marca']->prepend(self::$labels['marca_id'], '');
            $catalogs['producto']->prepend(self::$labels['producto_id'], '');
        } else {
            $catalogs['agencia']->prepend('', '');
            $catalogs['tipo_campana']->prepend('', '');
            $catalogs['industria']->prepend('', '');
            $catalogs['marca']->prepend('', '');
            $catalogs['producto']->prepend('', '');
        }

        return $catalogs;
    }

    public function hasMarca()
    {
        return !empty($this->marca_id);
    }

    public function hasProducto()
    {
        return !empty($this->producto_id);
    }

    /**
     *
     * @return App\Models\Agencia $agencia
     */
    public function agencia()
    {
        return $this->belongsTo('App\Models\Agencia', 'agencia_id', 'id');
    }

    /**
     *
     * @return App\Models\TipoCampana $tipoCampana
     */
    public function tipoCampana()
    {
        return $this->belongsTo('App\Models\TipoCampana', 'tipo_campana_id', 'id');
    }

    /**
     *
     * @return App\Models\Marca $marca
     */
    public function marca()
    {
        return $this->belongsTo('App\Models\Marca', 'marca_id', 'id');
    }

    /**
     *
     * @return App\Models\Producto $producto
     */
    public function producto()
    {
        return $this->belongsTo('App\Models\Producto', 'producto_id', 'id');
    }

    /**
     *
     * @return App\Models\Industria $industria
     */
    public function industria()
    {
        return $this->belongsTo('App\Models\Industria', 'industria_id', 'id');
    }

    /**
     *
     * @return App\Models\PublicacionXInfluenciadorXCampana $industria
     */
    public function pubXInfluXCamp()
    {
        return $this->hasMany('App\Models\PublicacionXInfluenciadorXCampana', 'campana_id', 'id');
    }

    /**
     *
     * @return App\Models\Influenciador[] $influenciadores
     */
    public function getInfluenciadores($estado = null)
    {
        $campana_id = $this->id;

        return Influenciador::select('influenciador.*')->join(
            'influenciador_x_campana',
            function ($join) use ($campana_id, $estado) {
                $query = $join->on(
                    'influenciador_x_campana.influenciador_id',
                    '=',
                    'influenciador.id'
                )->where('campana_id', $campana_id);

                if ($estado !== null) {
                    if (is_array($estado)) {
                        $query->whereIn('estado', $estado);
                    } else {
                        $query->where('estado', $estado);
                    }
                }
            }
        )->with('perfilTwitter', 'tipoInfluenciador')->get();
    }

    public function loadInfluenciadores()
    {
        $this->influenciadores = $this->getInfluenciadores();
    }

    /**
     *
     * @return App\Models\Influenciador[] $influenciadores
     */
    public function influenciadoresAprobados()
    {
        return $this->getInfluenciadores(InfluenciadorXCampana::$ACEPTADO);
    }

    public function loadInfluenciadoresAprobados()
    {
        $this->influenciadoresAprobados = $this->influenciadoresAprobados();
    }

    /**
     *
     * @return App\Models\Influenciador[] $influenciadores
     */
    public function influenciadoresPorAprobar()
    {
        return $this->getInfluenciadores([
            InfluenciadorXCampana::$ESPERANDO_RESPUESTA,
            InfluenciadorXCampana::$INSERTADO
        ]);
    }

    /**
     *
     * @return App\Models\Influenciador[] $influenciadores
     */
    public function influenciadoresAprobadosYPorAprobar()
    {
        return $this->getInfluenciadores([
            InfluenciadorXCampana::$ACEPTADO,
            InfluenciadorXCampana::$ESPERANDO_RESPUESTA
        ]);
    }

    /**
     * Guarda los influenciadores relacionados a la campaña
     *
     * @param  array $influenciadores
     * @param  boolean $update
     * @param  array $influenciadores_to_delete
     */
    public function saveInfluenciadores($influenciadores, $update = false, $influenciadores_to_delete = [])
    {
        // Elimina la asociacion entre influenciador y campaña
        InfluenciadorXCampana::where('campana_id', $this->id)
            ->whereIn('influenciador_id', $influenciadores_to_delete)
            ->delete();

        // Elimina todas las Publicaciones asociadas con el Influenciador y la Campaña
        PublicacionXInfluenciadorXCampana::where('campana_id', $this->id)
            ->whereIn('influenciador_id', $influenciadores_to_delete)
            ->delete();

        // Elimina el detalle de las Publicaciones
        Publicacion::where('campana_id', $this->id)
            ->whereIn('influenciador_id', $influenciadores_to_delete)
            ->delete();

        // Solo se procesa si se envia el listado de influenciadores
        if (count($influenciadores)) {
            foreach ($influenciadores as $influenciador) {
                $influenciadorCampana = InfluenciadorXCampana::where([
                        'influenciador_id' => $influenciador,
                        'campana_id'       => $this->id,
                    ])->first();

                if (empty($influenciadorCampana)) {
                    $influenciadorCampana = new InfluenciadorXCampana();
                }

resources/views/campanas/create.blade.php
@section('section_title', 'Registrar')

@include($response_info['resource'] . '._form', [
    'config_form' => [
        'id'                   => 'form-campana',
        'enctype'              => 'multipart/form-data',
        'model'                => $model,
        'store'                => $response_info['resource'] . '.store',
        'div_form_group_class' => 'col-xs-12 col-sm-12 col-md-12',
    ],
    'catalogs' => $catalogs,
])

resources/views/campanas/general_information.blade.php
@php
    // $model->getReport();
    $autolink = Twitter_Autolink::create();
@endphp

<div class="row border-bottom-gray">
    <div class="col-md-1 text-center">
        @if ($model->producto_id)
            <img src="{{ asset($model->producto->getImagen()) }}" class="img-campana img-circle">
        @elseif ($model->marca_id)
            <img src="{{ asset($model->marca->getLogotipo()) }}" class="img-campana img-circle">
        @else
            <img src="{{ asset($model->agencia->getLogotipo()) }}" class="img-campana img-circle">
        @endif
        <br>
        <strong>{{ $model->nombre }}</strong>
    </div>

    <div class="col-md-1 text-center">
        <p class="title-cam-g-info"><strong>@lang('campaign.objective')</strong></p><p>&nbsp;</p>
        <p>{{ $model->tipoCampana->tipo }}</p>
    </div>

    <div class="col-md-2 text-center">
        <p class="title-cam-g-info"><strong>@lang('campaign.hashtag')</strong></p><p>&nbsp;</p>
        <p class="color-light">{!! $autolink->autoLink($model->hashtags) !!}</p>
    </div>

    <div class="col-md-3 text-center">
        <p class="title-cam-g-info"><strong>@lang('campaign.posts')</strong></p><p>&nbsp;</p>
        <p>
            @php
                $postBySocialNetworks = $model->getCountPostBySocialNetwork();
            @endphp
            <img src="{{ asset('img/campana/twitter'.($postBySocialNetworks[\App\Models\RedSocial::$TWITTER]==0 ? '_gris' : '').'.png') }}" class="img-small">
                {{ $postBySocialNetworks[\App\Models\RedSocial::$TWITTER] }} &nbsp; &nbsp; &nbsp;
            <img src="{{ asset('img/campana/facebook'.($postBySocialNetworks[\App\Models\RedSocial::$FACEBOOK]==0 ? '_gris' : '').'.png') }}" class="img-small">
                {{ $postBySocialNetworks[\App\Models\RedSocial::$FACEBOOK] }} &nbsp; &nbsp; &nbsp;
            <img src="{{ asset('img/campana/instagram'.($postBySocialNetworks[\App\Models\RedSocial::$INSTAGRAM]==0 ? '_gris' : '').'.png') }}" class="img-small">
                {{ $postBySocialNetworks[\App\Models\RedSocial::$INSTAGRAM] }} &nbsp; &nbsp; &nbsp;
            <img src="{{ asset('img/campana/youtube'.($postBySocialNetworks[\App\Models\RedSocial::$YOUTUBE]==0 ? '_gris' : '').'.png') }}" class="img-small">
                {{ $postBySocialNetworks[\App\Models\RedSocial::$YOUTUBE] }}
        </p>
    </div>

    <div class="col-md-1 text-center">
        <p class="title-cam-g-info"><strong>@lang('campaign.influencers')</strong></p><p>&nbsp;</p>
        <p>{{ $model->getCountAutores() }}</p>
    </div>

    <div class="col-md-2 text-center">
        <p class="title-cam-g-info"><strong>@lang('campaign.campaign_duration')</strong></p>
        <table cellpadding="0" cellspacing="0" width="100%">
            <tr class="text-center">
                <td><span class="color-lightgray">To</span><br>@date_short($model->fecha_desde)</td>
                <td><span class="color-lightgray">From</span><br>@date_short($model->fecha_hasta)</td>
            </tr>
        </table>
    </div>

    <div class="col-md-2 text-center">
        <p class="title-cam-g-info"><strong>@lang('campaign.budget')</strong></p><p>&nbsp;</p>
        <p>{{ $model->presupuesto_currency }}</p>
    </div>
</div>

resources/views/campanas/index.blade.php
@extends('layouts.' . config('app.layout'))

@section('title', $title)

@section('content')
    <div class="panel panel-default">
        <div class="panel-body">

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <h3 class="title">MIS {{ strtoupper($title) }}</h3>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    {{-- Si se esta implementando Policy --}}
                    @if ($policy)
                        @can('create', $modelClass)
                        <p>
                            <a class="btn btn-red-rounded" href="{{ url($response_info['resource'] . '/create') }}" role="button">
                                <span class="glyphicon glyphicon-plus-sign"></span> Crear Campaña
                            </a>
                        </p>
                        @endcan
                    @else
                        <p>
                            <a class="btn btn-red-rounded" href="{{ url($response_info['resource'] . '/create') }}" role="button">
                                <span class="glyphicon glyphicon-plus-sign"></span> Crear Campaña
                            </a>
                        </p>
                    @endif
                </div>
            </div>

            @include($response_info['resource'] . '/_search', [
                'response_info' => $response_info,
                'lables' => $labels,
                'catalogs' => $catalogs,
            ])

            @include('common.errors', ['response_info' => $response_info])

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    {{ $models->appends(Request::query())->links() }}
                </div>

                @if (app('request')->has('filter'))
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="well well-sm text-success">
                            <span class="glyphicon glyphicon-zoom-in"></span> Resultados de la búsqueda
                        </div>
                    </div>
                @endif

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <p>Mostrando {{ $models->firstItem() }}-{{ $models->lastItem() }} de {{ $models->total() }} elementos.</p>
                </div>
            </div>

            @forelse ($models as $model)
                <div class="row black-box row-eq-height">
                    <div class="col-xs-8 col-sm-8 col-md-4">
                        <h2>
                            <a href="{{ url('campanas', $model->id) }}">{{ $model->nombre }}</a>
                        </h2>
                        <p class="light-gray">{{ $model->tipoCampana->tipo }}</p>
                        <p class="text-red">{{ $model->hashtags }}</p>
                        <p>
                            @include('common.options_xs', [
                                'policy' => $policy,
                                'modelClass' => $modelClass,
                                'model' => $model,
                                'url' => url($response_info['resource'] . '/' . $model->id)
                            ])
                            @if($model->tieneTerminosYCondiciones())
                                <a class="btn btn-red-circle btn-xs" data-toggle="tooltip" title="Ver términos y condiciones" href="{{ url($response_info['resource'] . '/' . $model->id) . '/terminos' }}"><i class="fa fa-file"></i></a>
                            @endif
                            <a class="btn btn-red-circle btn-xs" data-toggle="tooltip" title="Estadísticas" href="{{ url($response_info['resource'] . '/' . $model->id) . '/estadisticas' }}">
                                <i class="fa fa-bar-chart"></i>
                            </a>
                        </p>
                    </div>
                    <div class="col-xs-4 col-sm-4 col-md-2">
                        <br>
                        <table cellpadding="0" cellspacing="0">
                            <tr>
                                <td>
                                    <i class="fa fa-calendar fa-2x"></i>&nbsp; &nbsp;
                                </td>
                                <td>
                                    @date($model->fecha_desde)<br />
                                    @date($model->fecha_hasta)
                                </td>
                            </tr>
                        </table>
                        <br>
                        <p>
                            <i class="fa fa-credit-card fa-2x"></i>&nbsp;&nbsp;
                            {{ $model->presupuesto_currency }}
                        </p>
                    </div>
                    @php
                        $influenciadoresMostrar   = 4;
                        $influenciadoresAprobados = $model->influenciadoresAprobados();
                        $totalAprobados           = count($influenciadoresAprobados);
                        $influenciadoresPorAprobar = $model->influenciadoresPorAprobar();
                        $totalPorAprobar           = count($influenciadoresPorAprobar);
                    @endphp
                    {{-- Crea el espacio cuando no hay pendientes por aprobar --}}
                    @if ($totalPorAprobar == 0)
                        <div class="col-xs-6 col-sm-6 col-md-3"></div>
                    @endif
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        @if ($totalPorAprobar == 0 && $totalAprobados == 0)
                            <strong>NO SE ENCONTRARON INFLUENCERS PARA ESTA CAMPAÑA</strong>
                        @elseif ($totalPorAprobar == 0)
                            <strong>TODOS APROBADOS</strong>
                        @else
                            <strong>APROBADOS</strong>
                        @endif
                        <div>
                            @for ($i = 0; $i < $influenciadoresMostrar && $i < $totalAprobados; $i++)
                                @if ($influenciadoresAprobados[$i]->perfilTwitter)
                                    <img src="{{ str_replace('_normal', '', $influenciadoresAprobados[$i]->imgPerfil) }}" class="avatar small"
                                    data-toggle="tooltip" title="{{ $influenciadoresAprobados[$i]->nombre }}" data-id="{{ $influenciadoresAprobados[$i]->id }}">
                                @endif
                            @endfor

                            @if ($totalAprobados > $influenciadoresMostrar)
                                <span class="plus-influenciadores">+ {{ $totalAprobados - $influenciadoresMostrar }}</span>
                            @endif
                        </div>
                    </div>
                    {{-- Solo se muestra cuando hay pendientes por aprobar --}}
                    @if ($totalPorAprobar > 0)
                        <div class="col-xs-6 col-sm-6 col-md-3 gray-box">
                            <strong>POR APROBAR</strong>
                            <div>
                                @for ($i = 0; $i < $influenciadoresMostrar && $i < $totalPorAprobar; $i++)
                                    @if ($influenciadoresPorAprobar[$i]->perfilTwitter)
                                        <img src="{{ str_replace('_normal', '', $influenciadoresPorAprobar[$i]->imgPerfil) }}" class="avatar small"
                                        data-toggle="tooltip" title="{{ $influenciadoresPorAprobar[$i]->nombre }}" data-id="{{ $influenciadoresPorAprobar[$i]->id }}">
                                    @endif
                                @endfor

                                @if ($totalPorAprobar > $influenciadoresMostrar)
                                    <span class="plus-influenciadores">+ {{ $totalPorAprobar - $influenciadoresMostrar }}</span>
                                @endif
                            </div>
                        </div>
                    @endif
                </div>
            @empty
                <strong>No se encontraron campañas registradas.</strong>
            @endforelse

            <div class="text-center">
                {{ $models->appends(Request::query())->links() }}
            </div>
        </div>
    </div>
@endsection