routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');

// Sobreescribe la ruta de logout para que soporte get
Route::get('logout', function () {

    if (Auth::check()) {
        $isInfluencer = Auth::user()->isCelebridad();

        Auth::logout();
        request()->session()->flush();
        request()->session()->regenerate();

        if ($isInfluencer) {
            return redirect('influenciadores/login');
        }
    }

    return redirect('/');
});

Auth::routes();

Route::resource('servicios', 'ServiciosController');

Route::group(['prefix' => 'auth/twitter', 'namespace' => 'Auth'], function () {
    Route::get('login', 'TwitterController@redirectToProvider')->name('twitter.login');
    Route::get('logout', 'TwitterController@logout')->name('twitter.logout');
    Route::get('callback', 'TwitterController@handleProviderCallback')->name('twitter.callback');
    // Route::get('posttweet', 'TwitterController@postTweet')->name('twitter.post');
});

Route::group(['prefix' => 'auth/facebook', 'namespace' => 'Auth'], function () {
    Route::get('login', 'FacebookController@redirectToProvider')->name('facebook.login');
    Route::get('logout', 'FacebookController@logout')->name('facebook.logout');
    Route::get('callback', 'FacebookController@handleProviderCallback')->name('facebook.callback');
    Route::get('publicar', 'FacebookController@postTweet')->name('facebook.post');
});

Route::get('influenciadores/login', 'InfluenciadorController@login');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['perfil']], function () {
        Route::get('/', 'RedirectController@index')->name('index');
        Route::get('palabrasclaves/searchbytext', 'PalabraClaveController@searchByText');
        Route::get('agencias/logotipo', 'AgenciaController@getLogotipo');
        Route::get('agencias/home', 'AgenciaController@home');
        Route::get('marcas/logotipo', 'MarcaController@getLogotipo');
        Route::get('marcas/byagencia', 'MarcaController@getByAgencia');
        Route::get('productos/imagen', 'ProductoController@getImagen');
        Route::get('productos/bymarca', 'ProductoController@getByMarca');

        Route::get('influenciadores/vincular/twitter', 'VincularController@twitterRedirectToProvider');
        Route::get('influenciadores/vincular/twittercallback', 'VincularController@twitterHandleProviderCallback');
        Route::get('influenciadores/vincular/facebook', 'VincularController@facebookRedirectToProvider');
        Route::get('influenciadores/vincular/instagram', 'VincularController@instagramRedirectToProvider');
        Route::get('influenciadores/vincular/youtube', 'VincularController@youtubeRedirectToProvider');
        Route::get('influenciadores/vincular/snapchat', 'VincularController@snapchatRedirectToProvider');


        Route::get('influenciadores/miscampanas/{id}/posts', 'InfluenciadorController@miscampanasposts');
        Route::get('influenciadores/miscampanas', 'InfluenciadorController@miscampanas');
        Route::get('influenciadores/miinfo', 'InfluenciadorController@miinfo');
        Route::get('influenciadores/searchbytext', 'InfluenciadorController@searchByText');
        Route::get('influenciadores/advancedsearch', 'InfluenciadorController@advancedSearch');
        // Route::get('influenciadores/sincronizacion', 'InfluenciadorController@sincronizacion');
        // Route::get('influenciadores/sincronizarjsons', 'InfluenciadorController@sincronizarjsons');
        // Route::get('influenciadores/sincronizarperfil/{id}', 'InfluenciadorController@sincronizarperfil');
        Route::get('influenciadores/catalogo', 'InfluenciadorController@catalogo');
        Route::get('profile/general/{id}', 'ProfileController@getGeneral');
        Route::get('profile/crecimiento/{id}', 'ProfileController@getCrecimientoSeguidores');
        Route::get('profile/topseguidores/{id}', 'ProfileController@getTopSeguidores');
        Route::get('profile/topword/{id}', 'ProfileController@getTopWord');
        Route::get('profile/hashtag/{id}', 'ProfileController@getHashtag');
    });

    Route::post('/password/change', 'Auth\ChangePasswordController@update');
    Route::get('usuarios/perfil', 'UsuarioController@perfil')->name('usuarios.perfil');
    Route::put('usuarios/updateperfil/{id?}', 'UsuarioController@updateperfil')->name('usuarios.updateperfil');
    Route::resource('usuarios', 'UsuarioController');
    Route::resource('palabrasclaves', 'PalabraClaveController');

    Route::resource('agencias', 'AgenciaController');
    Route::resource('marcas', 'MarcaController');
    Route::resource('productos', 'ProductoController');

    Route::resource('campanas', 'CampanaController');
    Route::get('campanas/{id}/terminos', 'CampanaController@downloadTerminos');
    Route::get('campanas/{id}/estadisticas', 'CampanaController@estadisticas');
    Route::get('campanas/{id}/graficas/top-locations', 'CampanaController@graficaTopLocations');
    Route::get('campanas/{id}/graficas/posts-per-hour', 'CampanaController@graficaPostsPerHour');
    Route::get('campanas/{id}/graficas/share-social', 'CampanaController@graficaShareSocial');
    Route::get('campanas/{id}/graficas/shares-twitter', 'CampanaController@graficaSharesTwitter');

    Route::post('influenciadores/clic', 'InfluenciadorController@clic');
    Route::post('influenciadores/aprobarpublicaciones', 'InfluenciadorController@aprobarpublicaciones');
    //Route::get('influenciadores/searchlugarnacimientobytext', 'InfluenciadorController@searchLugarNacimientoByText');
    //Route::get('influenciadores/searchpaisbytext', 'InfluenciadorController@searchPaisByText');
    Route::resource('influenciadores', 'InfluenciadorController');

    Route::get('influenciadores/{influeciadore}/{q}', 'InfluenciadorController@showCustom');

    // estadísticas influencer profile
    Route::get('influenciadores/{id}/graficas/crecimiento-followers', 'InfluenciadorController@crecimientoFollowers');
    Route::get('influenciadores/{id}/graficas/interacciones-mes', 'InfluenciadorController@interaccionesMensual');

    Route::post('publicaciones/publicar/{id?}', 'PublicacionController@publicar');
    Route::post('publicaciones/aprobar', 'PublicacionController@aprobar');
    Route::resource('publicaciones', 'PublicacionController');

    Route::post('publicacionesxcampana/aceptarpropuesta', 'PublicacionXInfluenciadorXCampanaController@aceptarpropuesta');
    Route::post('publicacionesxcampana/rechazarpropuesta', 'PublicacionXInfluenciadorXCampanaController@rechazarpropuesta');
    Route::delete('publicacionesxcampana/destroy/{id?}', 'PublicacionXInfluenciadorXCampanaController@destroy');
    Route::put('publicacionesxcampana/update/{id?}', 'PublicacionXInfluenciadorXCampanaController@update');

    Route::post('influenciadoresxcampana/aceptarpropuesta', 'InfluenciadorXCampanaController@aceptarpropuesta');
    Route::post('influenciadoresxcampana/rechazarpropuesta', 'InfluenciadorXCampanaController@rechazarpropuesta');
    Route::delete('influenciadoresxcampana/destroy/{id?}', 'InfluenciadorXCampanaController@destroy');
    Route::put('influenciadoresxcampana/update/{id?}', 'InfluenciadorXCampanaController@update');

    Route::resource('chat', 'ChatController');

    Route::resource('logeventos', 'LogeventoController', ['only' => ['index']]);
});

app/Models/LogEvento.php
<?php

namespace App\Models;

use Auth;

class LogEvento extends BaseModel
{
    protected $table = 'log_evento';

    public static $INICIO_SESION = 1;
    public static $REGISTRO_USUARIO = 2;
    public static $REGISTRO_CAMPANA = 3;
    public static $OFERTA_CAMPANA_INFLUENCIADOR = 4;
    public static $ACEPTACION_CAMPANA_INFLUENCIADOR = 5;
    public static $CREACION_PUBLICACIONES = 6;
    public static $ACEPTACION_PUBLICACIONES_INFLUENCIADOR = 7;
    public static $RECHAZO_CAMPANA_INFLUENCIADOR = 8;

    public static $tipo = [
        1 => 'Inicio de Sesión',
        2 => 'Registro de Usuario/Influenciador',
        3 => 'Registro de Nueva Campaña',
        4 => 'Oferta de Campaña a Influenciador',
        5 => 'Aceptación de Ofertas de Campaña por Influenciador',
        6 => 'Creación de Publicaciones en Campaña',
        7 => 'Aceptación de Publicaciones por Influenciador',
        8 => 'Rechazo de Oferta de Campaña por Influenciador',
    ];

    protected $fillable = [
        'tipo',
        'campana_id',
        'usuario_id',
        'red_social_id',
        'created_by',
    ];

    public $rules_create = [
        'tipo'          => 'bail|required|integer|in:0,1,2,3,4,5,6,7',
        'campana_id'    => 'bail|nullable|integer|exists:campana,id',
        'usuario_id'    => 'bail|nullable|integer|exists:usuario,id',
        'red_social_id' => 'bail|nullable|integer|exists:red_social,id',
    ];

    public static $labels = [
        'tipo'          => 'Evento',
        'campana_id'    => 'Campaña',
        'usuario_id'    => 'Dirigido a',
        'red_social_id' => 'Red Social',
        'created_by'    => 'Usuario',
        'created_at'    => 'Fecha y Hora',
        // Campos extras, no pertenecen a la tabla
        'tipo_usuario'  => 'Tipo de Usuario',
        'fecha_desde'   => 'Desde',
        'fecha_hasta'   => 'Hasta',
    ];

    public $with = ['usuario', 'createdBy'];

    public function getTipoDescripcionAttribute($value)
    {
        return self::$tipo[$this->tipo];
    }

    /**
     * @return App\Models\User $usuario
     */
    public function usuario()
    {
        return $this->belongsTo('App\Models\User', 'usuario_id', 'id');
    }

    /**
     * @return App\Models\Agencia $agencia
     */
    public function agencia()
    {
        return $this->belongsTo('App\Models\Agencia', 'usuario_id', 'id');
    }

    /**
     * @return App\Models\Influenciador $influenciador
     */
    public function influenciador()
    {
        return $this->belongsTo('App\Models\Influenciador', 'usuario_id', 'id');
    }

    /**
     * @return App\Models\Campana $campana
     */
    public function campana()
    {
        return $this->belongsTo('App\Models\Campana', 'campana_id', 'id');
    }

    public static function getCatalogs($withLabels = true)
    {
        $catalogs = [];
        $catalogs['tipo'] = collect(self::$tipo);
        $catalogs['tipo']->prepend('', '');

        return $catalogs;
    }

    public function isInicioSesion()
    {
        return $this->tipo ==  self::$INICIO_SESION;
    }

    public function isRegistroUsuario()
    {
        return $this->tipo ==  self::$REGISTRO_USUARIO;
    }

    public function isRegistroCampana()
    {
        return $this->tipo ==  self::$REGISTRO_CAMPANA;
    }

    public function isOfertaCampanaInfluenciador()
    {
        return $this->tipo ==  self::$OFERTA_CAMPANA_INFLUENCIADOR;
    }

    public function isAceptacionCampanaInfluenciador()
    {
        return $this->tipo ==  self::$ACEPTACION_CAMPANA_INFLUENCIADOR;
    }

    public function isCreacionPublicaciones()
    {
        return $this->tipo ==  self::$CREACION_PUBLICACIONES;
    }

    public function isAceptacionPublicacionesInfluenciador()
    {
        return $this->tipo ==  self::$ACEPTACION_PUBLICACIONES_INFLUENCIADOR;
    }

    public static function saveInicioSesion()
    {
        self::create([
            'tipo' => self::$INICIO_SESION,
        ]);
    }

    public static function saveRegistroUsuario($usuario_id)
    {
        self::create([
            'tipo' => self::$REGISTRO_USUARIO,
            'usuario_id' => $usuario_id,
        ]);
    }

    public static function saveRegistroCampana($campana_id)
    {
        self::create([
            'tipo' => self::$REGISTRO_CAMPANA,
            'campana_id' => $campana_id,
        ]);
    }

    public static function saveOfertaCampanaInfluenciador($campana_id, $usuario_id, $red_social_id = null)
    {
        self::create([
            'tipo' => self::$OFERTA_CAMPANA_INFLUENCIADOR,
            'campana_id' => $campana_id,
            'usuario_id' => $usuario_id,
            'red_social_id' => $red_social_id,
        ]);
    }

    public static function saveAceptacionCampanaInfluenciador($campana_id)
    {
        self::create([
            'tipo' => self::$ACEPTACION_CAMPANA_INFLUENCIADOR,
            'campana_id' => $campana_id,
        ]);
    }

    public static function saveRechazoCampanaInfluenciador($campana_id, $red_social_id = null)
    {
        self::create([
            'tipo' => self::$RECHAZO_CAMPANA_INFLUENCIADOR,
            'campana_id' => $campana_id,
            'red_social_id' => $red_social_id,
        ]);
    }

    public static function saveCreacionPublicaciones($campana_id, $usuario_id, $red_social_id = null)
    {
        self::create([
            'tipo' => self::$CREACION_PUBLICACIONES,
            'campana_id' => $campana_id,
            'usuario_id' => $usuario_id,
            'red_social_id' => $red_social_id,
        ]);
    }

    public static function saveAceptacionPublicacionesInfluenciador($campana_id, $red_social_id = null)
    {
        self::create([
            'tipo' => self::$ACEPTACION_PUBLICACIONES_INFLUENCIADOR,
            'campana_id' => $campana_id,
            'red_social_id' => $red_social_id,
        ]);
    }

    /********************************************************************************
    Disable updated_at
    ********************************************************************************/
    public function setUpdatedAt($value){ }
    public function getUpdatedAtColumn(){ }
}

app/Http/Controllers/LogeventoController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Helper;
use App\Http\Controllers\BaseWebController;
use App\Models\Campana;
use App\Models\Genero;
use App\Models\Industria;
use App\Models\Influenciador;
use App\Models\RangoEtario;
use App\Models\SiNo;
use App\Models\TipoCampana;
use App\Models\TipoInfluenciador;
use Carbon\Carbon;
use DB;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LogeventoController extends BaseWebController
{
    public $modelClass = 'LogEvento';
    public $resource   = 'logeventos';
    public $title_sin  = 'Evento';
    public $title_plu  = 'Eventos';
    public $order_by   = 'created_at';

    public function onBeforeIndex(Request $request)
    {
        parent::onBeforeIndex($request);

        if ($request->has('filter.tipo')) {
            $this->filter[] = ['tipo', '=', $request->input('filter.tipo')];
        }

        if ($request->has('filter.fecha_desde')) {
            $this->filter[] = [
                'created_at',
                '>=',
                Carbon::createFromFormat(
                    'd-m-Y',
                    Helper::stripTags($request->input('filter.fecha_desde'))
                )->format('Y-m-d')
            ];
        }

        if ($request->has('filter.fecha_hasta')) {
            $this->filter[] = [
                'created_at',
                '<=',
                Carbon::createFromFormat(
                    'd-m-Y',
                    Helper::stripTags($request->input('filter.fecha_hasta'))
                )->format('Y-m-d')
            ];
        }
    }

    public function index(Request $request)
    {
        // Solo obtiene todos los eventos generados o dirigidos por la Agencia
        if (Auth::user()->isAgencia()) {
            $this->filter[] = ['created_by', '=', Auth::user()->id, true];
            $this->filter[] = ['usuario_id', '=', Auth::user()->id, true];
        }

        $request->merge([
            'order_direction' => 'DESC',
        ]);

        return parent::index($request);
    }
}

resources/views/logeventos/_search.blade.php
@extends('layouts.' . config('app.layout') . '_search')

@section('search')
    {!! BootForm::horizontal([
            'method' => 'GET',
            'url' => url($response_info['resource']),
        ])
    !!}

        {!! BootForm::text('filter[fecha_desde]', $labels['fecha_desde'],
                app('request')->input('filter.fecha_desde'), [
                    'class' => 'datepicker',
                ]
            )
        !!}

        {!! BootForm::text('filter[fecha_hasta]', $labels['fecha_hasta'],
                app('request')->input('filter.fecha_hasta'), [
                    'class' => 'datepicker',
                ]
            )
        !!}

        {!! BootForm::select('filter[tipo]', $labels['tipo'],
                $catalogs['tipo'], app('request')->input('filter.tipo'), []
            )
        !!}

        <div class="form-group col-xs-12 col-md-12 text-center">
            {!! Form::button('<span class="glyphicon glyphicon-search"></span> Buscar', [
                    'type' => 'submit',
                    'class' => 'btn btn-red-rounded',
                ]) !!} &nbsp;
            <a class="btn btn-default" href="{{ url($response_info['resource']) }}" role="button">
                <span class="glyphicon glyphicon-list"></span> Listar todos
            </a>
        </div>

    {!! BootForm::close() !!}
@endsection

resources/views/logeventos/index.blade.php
@extends('layouts.' . config('app.layout'))

@section('title', $title)

@section('content')
    <div class="panel panel-default">
        <div class="panel-body">

            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <h3 class="title">{{ strtoupper($title) }}</h3>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    {{-- Si se esta implementando Policy --}}
                    @if ($policy)
                        @can('create', $modelClass)
                        <p>
                            <a class="btn btn-red-rounded" href="{{ url($response_info['resource'] . '/create') }}" role="button">
                                <span class="glyphicon glyphicon-plus-sign"></span> Registrar
                            </a>
                        </p>
                        @endcan
                    @else
                        <p>
                            <a class="btn btn-red-rounded" href="{{ url($response_info['resource'] . '/create') }}" role="button">
                                <span class="glyphicon glyphicon-plus-sign"></span> Registrar
                            </a>
                        </p>
                    @endif
                </div>
            </div>

            @include($response_info['resource'] . '/_search', [
                'response_info' => $response_info,
                'lables' => $labels,
                'catalogs' => $catalogs,
            ])

            @include('common.errors', ['response_info' => $response_info])

            <div class="text-center">
                {{ $models->appends(Request::query())->links() }}
            </div>

            @if (app('request')->input('filter'))
                <div class="well well-sm text-success">
                    <span class="glyphicon glyphicon-zoom-in"></span> Resultados de la búsqueda
                </div>
            @endif

            Mostrando {{ $models->firstItem() }}-{{ $models->lastItem() }} de {{ $models->total() }} elementos.

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th style="width: 40px;" class="text-center"></th>
                        <th>{{ $labels['created_by'] }}</th>
                        <th>{{ $labels['tipo_usuario'] }}</th>
                        <th>{{ $labels['tipo'] }}</th>
                        <th>{{ $labels['created_at'] }}</th>
                        <th>{{ $labels['campana_id'] }}</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $i = 0; ?>
                    @forelse ($models as $model)
                        <tr>
                            <td class="text-center">{{ $models->firstItem() + ($i++) }}</td>
                            <td>{{ $model->createdBy ? $model->createdBy->nombre : '' }}</td>
                            <td>{{ $model->createdBy ? $model->createdBy->tipoUsuario->descripcion : '' }}</td>
                            <td>{{ $model->tipo_descripcion }}</td>
                            <td>@datetime($model->created_at)</td>
                            <td>{{ $model->campana ? $model->campana->nombre : '' }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6">No se encontrarón datos.</td>
                        </tr>
                    @endforelse

                </tbody>
            </table>

            <div class="text-center">
                {{ $models->appends(Request::query())->links() }}
            </div>
        </div>
    </div>
@endsection